# frozen_string_literal: true

source 'https://rubygems.org'

# gem "rails"

gem 'google-protobuf'
gem 'http'
gem 'puma'
gem 'reel'
gem 'ruby-kafka'
gem 'sinatra'
gem 'thin'
gem 'webrick'
gem 'grpc'
gem 'grpc-tools'