# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trade.proto

require 'user_pb'
require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("trade.proto", :syntax => :proto3) do
    add_message "Trade" do
      optional :id, :string, 1
      optional :symbol, :string, 2
      optional :amount, :double, 3
      optional :status, :string, 4
      optional :user, :message, 5, "User"
    end
    add_message "GetTradeStatusRequest" do
      optional :id, :string, 1
    end
    add_message "GetTradeStatusResponse" do
      optional :trade, :message, 1, "Trade"
      optional :request, :message, 2, "GetTradeStatusRequest"
    end
  end
end

Trade = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Trade").msgclass
GetTradeStatusRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetTradeStatusRequest").msgclass
GetTradeStatusResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetTradeStatusResponse").msgclass
