# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: trade.proto for package ''

require 'grpc'
require 'trade_pb'

module TradeService
  class Service

    include ::GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'TradeService'

    rpc :GetTradeStatus, ::GetTradeStatusRequest, ::GetTradeStatusResponse
  end

  Stub = Service.rpc_stub_class
end
