# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("user.proto", :syntax => :proto3) do
    add_message "User" do
      optional :id, :string, 1
      optional :username, :string, 2
    end
    add_message "LoginRequest" do
      optional :username, :string, 1
      optional :password, :string, 2
    end
    add_message "LoginResponse" do
      optional :status, :string, 1
      optional :key, :string, 2
    end
    add_message "LogoutRequest" do
      optional :username, :string, 1
    end
    add_message "LogoutResponse" do
      optional :status, :string, 1
    end
  end
end

User = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("User").msgclass
LoginRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("LoginRequest").msgclass
LoginResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("LoginResponse").msgclass
LogoutRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("LogoutRequest").msgclass
LogoutResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("LogoutResponse").msgclass
