# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: user.proto for package ''

require 'grpc'
require 'user_pb'

module UserService
  class Service

    include ::GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'UserService'

    rpc :Login, ::LoginRequest, ::LoginResponse
    rpc :Logout, ::LogoutRequest, ::LogoutResponse
  end

  Stub = Service.rpc_stub_class
end
